/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Strategy.difficultyStrategy.EasyDifficulty;
import model.Strategy.difficultyStrategy.HardDifficulty;
import model.Strategy.difficultyStrategy.MediumDifficulty;

/**
 *
 * @author ADMIN
 */
public class ChooseDifficulty extends javax.swing.JFrame {
    private static ChooseDifficulty instance = null;
    private Circus circus;
    /**
     * Creates new form ChooseDifficulty
     */
    private ChooseDifficulty() {
        initComponents();
    }
    public static ChooseDifficulty getChooseDifficultyView() {
        if (instance == null) {
            instance = new ChooseDifficulty();
        }
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        easyButton = new javax.swing.JButton();
        mediumButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose Difficulty");
        getContentPane().setLayout(null);

        easyButton.setBackground(new java.awt.Color(102, 0, 0));
        easyButton.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        easyButton.setForeground(new java.awt.Color(255, 255, 255));
        easyButton.setText("EASY");
        easyButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(easyButton);
        easyButton.setBounds(320, 160, 290, 90);

        mediumButton.setBackground(new java.awt.Color(102, 0, 0));
        mediumButton.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        mediumButton.setForeground(new java.awt.Color(255, 255, 255));
        mediumButton.setText("MEDIUM");
        mediumButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mediumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mediumButton);
        mediumButton.setBounds(320, 270, 290, 90);

        hardButton.setBackground(new java.awt.Color(102, 0, 0));
        hardButton.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        hardButton.setForeground(new java.awt.Color(255, 255, 255));
        hardButton.setText("HARD");
        hardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hardButton);
        hardButton.setBounds(320, 380, 290, 90);

        returnButton.setBackground(new java.awt.Color(0, 0, 0));
        returnButton.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        returnButton.setForeground(new java.awt.Color(255, 255, 255));
        returnButton.setText("Return");
        returnButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton);
        returnButton.setBounds(320, 500, 290, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circus3.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 950, 670);

        setSize(new java.awt.Dimension(953, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        // TODO add your handling code here:
        
        Controller.Difficulty.setDifficulty(new EasyDifficulty());
        circus = Circus.getCircus();
        circus.init();
        
        this.setVisible(false);
    }//GEN-LAST:event_easyButtonActionPerformed

    private void mediumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumButtonActionPerformed
        // TODO add your handling code here:
        
        Controller.Difficulty.setDifficulty(new MediumDifficulty());
        circus = Circus.getCircus();
        circus.init();
        
        this.setVisible(false);
    }//GEN-LAST:event_mediumButtonActionPerformed

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        // TODO add your handling code here:

        Controller.Difficulty.setDifficulty(new HardDifficulty());
        circus = Circus.getCircus();
        circus.init();
        
        this.setVisible(false);
    }//GEN-LAST:event_hardButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        MainMenuView.getMainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mediumButton;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
